const metrics = [
  { label: 'Qualified candidates', value: '128', detail: '+14 from last week' },
  { label: 'Average match score', value: '89%', detail: 'Strong alignment with role' },
  { label: 'Time saved', value: '7.2h', detail: 'Per recruiter per week' },
];

const shortlisted = [
  { name: 'Ava Patel', role: 'Senior Frontend Engineer', score: '96', status: 'Top Match' },
  { name: 'Marcus Lee', role: 'Product Designer', score: '91', status: 'Strong Fit' },
  { name: 'Nora Kim', role: 'Data Analyst', score: '88', status: 'Recommended' },
];

export default function DashboardPage() {
  return (
    <section className="space-y-6">
      <div className="rounded-[2rem] border border-white/10 bg-slate-900/70 p-6 shadow-[0_16px_50px_rgba(0,0,0,0.25)] backdrop-blur-xl">
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.28em] text-cyan-300">Dashboard</p>
            <h1 className="mt-2 text-3xl font-semibold text-white">Recruiting insights at a glance</h1>
            <p className="mt-3 max-w-2xl text-slate-400">Monitor candidate quality, ranking confidence, and team efficiency in one place.</p>
          </div>
          <div className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-4 py-2 text-sm text-emerald-300">
            AI rank confidence 92%
          </div>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        {metrics.map((metric) => (
          <div key={metric.label} className="rounded-[1.5rem] border border-white/10 bg-white/8 p-5 shadow-[0_10px_35px_rgba(0,0,0,0.2)] backdrop-blur-lg">
            <p className="text-sm text-slate-400">{metric.label}</p>
            <p className="mt-3 text-3xl font-semibold text-white">{metric.value}</p>
            <p className="mt-2 text-sm text-cyan-300">{metric.detail}</p>
          </div>
        ))}
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]">
        <div className="rounded-[2rem] border border-white/10 bg-slate-900/70 p-6 shadow-[0_16px_50px_rgba(0,0,0,0.25)] backdrop-blur-xl">
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h2 className="text-xl font-semibold text-white">Top ranked candidates</h2>
              <p className="text-sm text-slate-400">A curated shortlist generated by the AI system</p>
            </div>
            <button className="rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300 transition hover:bg-white/10 hover:text-white">
              Export list
            </button>
          </div>

          <div className="space-y-3">
            {shortlisted.map((candidate) => (
              <div key={candidate.name} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="font-semibold text-white">{candidate.name}</p>
                  <p className="text-sm text-slate-400">{candidate.role}</p>
                </div>
                <div className="flex items-center gap-3">
                  <div className="rounded-full bg-cyan-400/10 px-3 py-1 text-sm text-cyan-300">{candidate.status}</div>
                  <div className="text-lg font-semibold text-white">{candidate.score}%</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-[2rem] border border-white/10 bg-slate-900/70 p-6 shadow-[0_16px_50px_rgba(0,0,0,0.25)] backdrop-blur-xl">
          <p className="text-sm font-semibold uppercase tracking-[0.24em] text-cyan-300">Highlights</p>
          <h2 className="mt-2 text-xl font-semibold text-white">What the platform is doing well</h2>
          <div className="mt-6 space-y-4">
            {[
              ['Skill relevance', '92%'],
              ['Experience alignment', '87%'],
              ['Communication fit', '84%'],
            ].map(([label, value]) => (
              <div key={label}>
                <div className="mb-2 flex items-center justify-between text-sm">
                  <span className="text-slate-300">{label}</span>
                  <span className="text-cyan-300">{value}</span>
                </div>
                <div className="h-2 rounded-full bg-slate-800">
                  <div className="h-2 rounded-full bg-gradient-to-r from-cyan-400 to-violet-500" style={{ width: value }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
